# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastLambda <- function(D, C) {
    .Call(`_SparseDFM_fastLambda`, D, C)
}

#' Standard Multivariate KFS Equations
#'
#' @param X n x p, numeric matrix of (stationary) time series 
#' @param a0_0 k x 1, initial state mean vector 
#' @param P0_0 k x k, initial state covariance matrix
#' @param A k x k, state transition matrix
#' @param Lambda p x k, measurement matrix 
#' @param Sig_e p x p, measurement equation residuals covariance matrix (diagonal)
#' @param Sig_u k x k, state equation residuals covariance matrix
#' @export
kalmanCpp <- function(X, a0_0, P0_0, A, Lambda, Sig_e, Sig_u) {
    .Call(`_SparseDFM_kalmanCpp`, X, a0_0, P0_0, A, Lambda, Sig_e, Sig_u)
}

#' Univariate filtering (sequential processing) for fast KFS
#'
#' @param X n x p, numeric matrix of (stationary) time series 
#' @param a0_0 k x 1, initial state mean vector 
#' @param P0_0 k x k, initial state covariance matrix
#' @param A k x k, state transition matrix
#' @param Lambda p x k, measurement matrix 
#' @param Sig_e p x p, measurement equation residuals covariance matrix (diagonal)
#' @param Sig_u k x k, state equation residuals covariance matrix
#' @export
kalmanUnivariate <- function(X, a0_0, P0_0, A, Lambda, Sig_e, Sig_u) {
    .Call(`_SparseDFM_kalmanUnivariate`, X, a0_0, P0_0, A, Lambda, Sig_e, Sig_u)
}

softThreshScalar <- function(X, thresh) {
    .Call(`_SparseDFM_softThreshScalar`, X, thresh)
}

softThreshMatrix <- function(X, thresh) {
    .Call(`_SparseDFM_softThreshMatrix`, X, thresh)
}

solveCube <- function(A, B, nu = 0.0) {
    .Call(`_SparseDFM_solveCube`, A, B, nu)
}

