# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
fastLambda <- function(D, C) {
    .Call('_SparseDFM_fastLambda', PACKAGE = 'SparseDFM', D, C)
}

#' @export
kalmanCpp <- function(X, a0_0, P0_0, A, Lambda, Sig_e, Sig_u) {
    .Call('_SparseDFM_kalmanCpp', PACKAGE = 'SparseDFM', X, a0_0, P0_0, A, Lambda, Sig_e, Sig_u)
}

#' @export
kalmanUnivariate <- function(X, a0_0, P0_0, A, Lambda, Sig_e, Sig_u) {
    .Call('_SparseDFM_kalmanUnivariate', PACKAGE = 'SparseDFM', X, a0_0, P0_0, A, Lambda, Sig_e, Sig_u)
}

#' @export
softThreshScalar <- function(X, thresh) {
    .Call('_SparseDFM_softThreshScalar', PACKAGE = 'SparseDFM', X, thresh)
}

#' @export
softThreshMatrix <- function(X, thresh) {
    .Call('_SparseDFM_softThreshMatrix', PACKAGE = 'SparseDFM', X, thresh)
}

#' @export
solveCube <- function(A, B, nu = 0.0) {
    .Call('_SparseDFM_solveCube', PACKAGE = 'SparseDFM', A, B, nu)
}

